// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTkE8EMsLdm0rjlfdKcaKI2KdHc8UtHZQ',
    appId: '1:642510020139:web:b5b61d972433b2a838d46e',
    messagingSenderId: '642510020139',
    projectId: 'roundnet-trainer-app',
    authDomain: 'roundnet-trainer-app.firebaseapp.com',
    storageBucket: 'roundnet-trainer-app.appspot.com',
    measurementId: 'G-WH7Q1H2DFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEsn3FLT6z_0qTPpR_5Q-5xH0N2Hibmyg',
    appId: '1:642510020139:android:363c3e449f5b0e4b38d46e',
    messagingSenderId: '642510020139',
    projectId: 'roundnet-trainer-app',
    storageBucket: 'roundnet-trainer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUG3okYM9-UDn6HPUQWw1-goex8In_qG4',
    appId: '1:642510020139:ios:1689f4093151739c38d46e',
    messagingSenderId: '642510020139',
    projectId: 'roundnet-trainer-app',
    storageBucket: 'roundnet-trainer-app.appspot.com',
    iosClientId:
        '642510020139-ib3vlru4nrvr6oet5c1hlfl0docilv9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUG3okYM9-UDn6HPUQWw1-goex8In_qG4',
    appId: '1:642510020139:ios:1689f4093151739c38d46e',
    messagingSenderId: '642510020139',
    projectId: 'roundnet-trainer-app',
    storageBucket: 'roundnet-trainer-app.appspot.com',
    iosClientId:
        '642510020139-ib3vlru4nrvr6oet5c1hlfl0docilv9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
